export const LOGIN_ACTION_TYPE = {
    LOGIN: 'USER_LOGIN',
    LOGOUT: 'USER_LOGOUT'
}

export const TRANSACTION_ACTION_TYPE = {
    ADD_ORDER: 'ADD_ORDER',
    CLEAR_ORDER: 'CLEAR_ORDER',
    SUBMIT_ORDER: 'SUBMIT_ORDER',
    CATALOGUE_ORDER: 'CATALOGUE_ORDER',
}

